### ISSUE TITLE
Runner.js not accepting mocha options

### ISSUE THREAD

**Issue by eighteyes** [balderdashy/sails-adapter-boilerplate#8]
Can't change my reporter. I want to see my passing tests!

**Comment by dmarcelino** [comment]
Hi eighteyes, you can change your reporter by adding a mocha options object to your runner.js options, example:

``` javascript
    // Mocha options
    // reference: https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically
    mocha: {
      reporter: 'spec',
    }
```

Waterline-adapter-tests will pass it to the mocha instance.

**Comment by eighteyes** [comment]
I just included it in the mocha.opts
